title: GeckoLasso
description: >-
  Gecko-adhesion-inspired grasping and retrieval systems research.
url: "https://emjmakesstuff.github.io"
baseurl: "/geckolasso.github.io"

theme: minima

minima:
  skin: classic
  social_links:
    - platform: github
      user_url: "https://github.com/geckolasso"

email: lab@geckolasso.example.edu

header_pages:
  - publications.html
  - team.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - node_modules
